import { Inter } from "next/font/google";
import "./globals.css";
import "../sass/style.scss"
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import CustomCursor from "@/components/CustomCursor/CustomCursor";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Davis - Personal Portfolio NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      '/favicon.ico?v=4',
    ],
    apple: [
      '/apple-touch-icon.png?v=4',
    ],
    shortcut: [
      '/apple-touch-icon.png'
    ]
  },
  manifest: '/site.webmanifest'
  
};



export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
  );
}
